spring.application.name=db_kiemtra
spring.datasource.url=jdbc:mysql://localhost:3306/db_kiemtra?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Google OAuth2 Configuration (Câu 9)
spring.security.oauth2.client.registration.google.client-id=669991196046-9c82f7ujtii465t4rt7joior0c3ro861.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google